### ISSUE TITLE
Download URL fixed

### ISSUE THREAD

**Issue by tarocjsu** [darkthread/ClassicIE#1]
這裡：
https://blog.darkthread.net/blog/build-net6-projects-for-dummies/

裡頭的
[.NET 6 SDK](https://dotnet.microsoft.com/en-us/download?WT.mc_id=DOP-MVP-37580) (.NET SDK 唸法為「搭內 S-D-K)

會被導去下載最新版本的SDK，例如8.0版本的dotnet-sdk-8.0.201-win-x64.exe

發現這個Project一定得用6.0版本的SDK不可，所以正確的下載URL會是：
https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Comment by darkthread** [comment]
已升級到 .NET 8，文章下載處也加了註解，感謝通報。
